const 시스템_개발자 = {
  ShareNotice: 6,
  MasterUser: 6,
  MasterClient: 6,
  MasterProduct: 6,
  MasterBOM: 6,
  MasterFacility: 6,
  MasterProcess: 6,
  MasterMold: 6,
  MasterCodeBad: 6,
  MasterCodeNonOP: 6,
  MasterFacilityParts: 6,
  MasterQualityStd: 6,
  MasterFacilityStd: 6,
  MasterStockStd: 6,
  MasterRecipe: 6,
  OrderAdd: 6,
  OrderCurrent: 6,
  OrderForecast: 6,
  OrderNotify: 6,
  OrderDelivery: 6,
  OrderOrder: 6,
  OrderOrderCurrent: 6,
  OrderFacilityParts: 6,
  OrderFacilityPartsCurrent: 6,
  ProductionPlanAdd: 6,
  ProductionTaskAdd: 6,
  ProductionTaskCurrent: 6,
  ProductionTaskReport: 6,
  ProductionBadRework: 6,
  ProcessLOT: 6,
  ProcessLOTTrack: 6,
  ProcessChecker: 6,
  ProcessPlate: 6,
  ProcessPrinter1: 6,
  ProcessPrinter2: 6,
  ProcessPrinter3: 6,
  ProcessPrinter4: 6,
  ProcessPrinter5: 6,
  ProcessPrinter6: 6,
  ProcessPrinter7: 6,
  ProcessPrinter8: 6,
  StockReceiveRaw: 6,
  StockWIPRaw: 6,
  StockWIPMonitorRaw: 6,
  StockUseRaw: 6,
  StockMonitorRaw: 6,
  StockReceiveHalf: 6,
  StockWIPHalf: 6,
  StockWIPMonitorHalf: 6,
  StockUseHalf: 6,
  StockMonitorHalf: 6,
  StockReceiveFinish: 6,
  StockMonitorFinish: 6,
  StockReceiveParts: 6,
  StockUseParts: 6,
  StockMonitorParts: 6,
  QualityStandard: 6,
  QualityReport: 6,
  QualityIncoming: 6,
  QualityProcess: 6,
  QualityShipment: 6,
  MoldUse: 6,
  MoldRepair: 6,
  MoldCheck: 6,
  MonitoringKPI1: 6,
  MonitoringKPI2: 6,
  MonitoringDaily: 6,
  MonitoringPrevent: 6,
  MonitoringMTBF: 6,
  MonitoringMTTR: 6,
  MonitoringOEE: 6,
  PreventPlan: 6,
  PreventDailyPlan: 6,
  PreventRepairPlan: 6,
  PreventLifePlan: 6,
  PreventForecast: 6,
  PreventNotice: 6,
  PreventErrorNotify: 6,
  PreventDailyNotify: 6,
  PreventRepairForecast: 6,
  PreventRepairNotify: 6,
  PreventChangeNotify: 6,
  AdminLog: 6,
  AlertOrderForecast: 6,
  AlertOrderNotify: 6,
  AlertPreventForecast: 6,
  AlertPreventNotice: 6,
  AlertPreventErrorNotify: 6,
  AlertPreventDailyNotify: 6,
  AlertPreventRepairForecast: 6,
  AlertPreventRepairNotify: 6,
  AlertPreventChangeNotify: 6,
  AlertStockSafeNotify: 6,
  MobileOrderCurrentForecast: 6,
  MobileOrderCurrentNotify: 6,
  MobileOrderTaskReport: 6,
  MobileStockReceive: 6,
  MobileStockDelivery: 6,
  MobileStockLOTPrint: 6,
  MobileStockLOTTrack: 6,
  MobileStockSafeNotify: 6,
  MobilePreventDailyCheck: 6,
  MobilePreventDailyCheckNotify: 6,
  MobilePreventForecast: 6,
  MobilePreventNotify: 6,
  MobilePreventRepairForecast: 6,
  MobilePreventRepairNotify: 6,
  MobilePreventChangeNotify: 6,
  MobilePreventErrorNotify: 6,
};

const 시스템_관리자 = {
  ShareNotice: 5,
  MasterUser: 5,
  MasterClient: 5,
  MasterProduct: 5,
  MasterBOM: 5,
  MasterFacility: 5,
  MasterProcess: 5,
  MasterMold: 5,
  MasterCodeBad: 5,
  MasterCodeNonOP: 5,
  MasterFacilityParts: 5,
  MasterQualityStd: 5,
  MasterFacilityStd: 5,
  MasterStockStd: 5,
  MasterRecipe: 5,
  OrderAdd: 5,
  OrderCurrent: 5,
  OrderForecast: 5,
  OrderNotify: 5,
  OrderDelivery: 5,
  OrderOrder: 5,
  OrderOrderCurrent: 5,
  OrderFacilityParts: 5,
  OrderFacilityPartsCurrent: 5,
  ProductionPlanAdd: 5,
  ProductionTaskAdd: 5,
  ProductionTaskCurrent: 5,
  ProductionTaskReport: 5,
  ProductionBadRework: 5,
  ProcessLOT: 5,
  ProcessLOTTrack: 5,
  ProcessChecker: 5,
  ProcessPlate: 5,
  ProcessPrinter1: 5,
  ProcessPrinter2: 5,
  ProcessPrinter3: 5,
  ProcessPrinter4: 5,
  ProcessPrinter5: 5,
  ProcessPrinter6: 5,
  ProcessPrinter7: 5,
  ProcessPrinter8: 5,
  StockReceiveRaw: 5,
  StockWIPRaw: 5,
  StockWIPMonitorRaw: 5,
  StockUseRaw: 5,
  StockMonitorRaw: 5,
  StockReceiveHalf: 5,
  StockWIPHalf: 5,
  StockWIPMonitorHalf: 5,
  StockUseHalf: 5,
  StockMonitorHalf: 5,
  StockReceiveFinish: 5,
  StockMonitorFinish: 5,
  StockReceiveParts: 5,
  StockUseParts: 5,
  StockMonitorParts: 5,
  QualityStandard: 5,
  QualityReport: 5,
  QualityIncoming: 5,
  QualityProcess: 5,
  QualityShipment: 5,
  MoldUse: 5,
  MoldRepair: 5,
  MoldCheck: 5,
  MonitoringKPI1: 5,
  MonitoringKPI2: 5,
  MonitoringDaily: 5,
  MonitoringPrevent: 5,
  MonitoringMTBF: 5,
  MonitoringMTTR: 5,
  MonitoringOEE: 5,
  PreventPlan: 5,
  PreventDailyPlan: 5,
  PreventRepairPlan: 5,
  PreventLifePlan: 5,
  PreventForecast: 5,
  PreventNotice: 5,
  PreventErrorNotify: 5,
  PreventDailyNotify: 5,
  PreventRepairForecast: 5,
  PreventRepairNotify: 5,
  PreventChangeNotify: 5,
  AdminLog: 5,
  AlertOrderForecast: 5,
  AlertOrderNotify: 5,
  AlertPreventForecast: 5,
  AlertPreventNotice: 5,
  AlertPreventErrorNotify: 5,
  AlertPreventDailyNotify: 5,
  AlertPreventRepairForecast: 5,
  AlertPreventRepairNotify: 5,
  AlertPreventChangeNotify: 5,
  AlertStockSafeNotify: 5,
  MobileOrderCurrentForecast: 5,
  MobileOrderCurrentNotify: 5,
  MobileOrderTaskReport: 5,
  MobileStockReceive: 5,
  MobileStockDelivery: 5,
  MobileStockLOTPrint: 5,
  MobileStockLOTTrack: 5,
  MobileStockSafeNotify: 5,
  MobilePreventDailyCheck: 5,
  MobilePreventDailyCheckNotify: 5,
  MobilePreventForecast: 5,
  MobilePreventNotify: 5,
  MobilePreventRepairForecast: 5,
  MobilePreventRepairNotify: 5,
  MobilePreventChangeNotify: 5,
  MobilePreventErrorNotify: 5,
};

const 영업_관리자 = {
  ShareNotice: 5,
  MasterUser: 5,
  MasterClient: 5,
  MasterProduct: 5,
  MasterBOM: 5,
  MasterFacility: 5,
  MasterProcess: 5,
  MasterMold: 5,
  MasterCodeBad: 5,
  MasterCodeNonOP: 5,
  MasterFacilityParts: 5,
  MasterQualityStd: 5,
  MasterFacilityStd: 5,
  MasterStockStd: 5,
  MasterRecipe: 5,
  OrderAdd: 5,
  OrderCurrent: 5,
  OrderForecast: 5,
  OrderNotify: 5,
  OrderDelivery: 5,
  OrderOrder: 5,
  OrderOrderCurrent: 5,
  OrderFacilityParts: 5,
  OrderFacilityPartsCurrent: 5,
  ProductionPlanAdd: 5,
  ProductionTaskAdd: 5,
  ProductionTaskCurrent: 5,
  ProductionTaskReport: 5,
  ProductionBadRework: 5,
  ProcessLOT: 5,
  ProcessLOTTrack: 5,
  ProcessChecker: 5,
  ProcessPlate: 5,
  ProcessPrinter1: 5,
  ProcessPrinter2: 5,
  ProcessPrinter3: 5,
  ProcessPrinter4: 5,
  ProcessPrinter5: 5,
  ProcessPrinter6: 5,
  ProcessPrinter7: 5,
  ProcessPrinter8: 5,
  StockReceiveRaw: 5,
  StockWIPRaw: 5,
  StockWIPMonitorRaw: 5,
  StockUseRaw: 5,
  StockMonitorRaw: 5,
  StockReceiveHalf: 5,
  StockWIPHalf: 5,
  StockWIPMonitorHalf: 5,
  StockUseHalf: 5,
  StockMonitorHalf: 5,
  StockReceiveFinish: 5,
  StockMonitorFinish: 5,
  StockReceiveParts: 5,
  StockUseParts: 5,
  StockMonitorParts: 5,
  QualityStandard: 5,
  QualityReport: 5,
  QualityIncoming: 5,
  QualityProcess: 5,
  QualityShipment: 5,
  MoldUse: 5,
  MoldRepair: 5,
  MoldCheck: 5,
  MonitoringKPI1: 5,
  MonitoringKPI2: 5,
  MonitoringDaily: 5,
  MonitoringPrevent: 5,
  MonitoringMTBF: 5,
  MonitoringMTTR: 5,
  MonitoringOEE: 5,
  PreventPlan: 5,
  PreventDailyPlan: 5,
  PreventRepairPlan: 5,
  PreventLifePlan: 5,
  PreventForecast: 5,
  PreventNotice: 5,
  PreventErrorNotify: 5,
  PreventDailyNotify: 5,
  PreventRepairForecast: 5,
  PreventRepairNotify: 5,
  PreventChangeNotify: 5,
  AdminLog: 1,
  AlertOrderForecast: 1,
  AlertOrderNotify: 1,
  AlertPreventForecast: 1,
  AlertPreventNotice: 1,
  AlertPreventErrorNotify: 1,
  AlertPreventDailyNotify: 1,
  AlertPreventRepairForecast: 1,
  AlertPreventRepairNotify: 1,
  AlertPreventChangeNotify: 1,
  AlertStockSafeNotify: 1,
  MobileOrderCurrentForecast: 5,
  MobileOrderCurrentNotify: 5,
  MobileOrderTaskReport: 5,
  MobileStockReceive: 5,
  MobileStockDelivery: 5,
  MobileStockLOTPrint: 5,
  MobileStockLOTTrack: 5,
  MobileStockSafeNotify: 5,
  MobilePreventDailyCheck: 5,
  MobilePreventDailyCheckNotify: 5,
  MobilePreventForecast: 5,
  MobilePreventNotify: 5,
  MobilePreventRepairForecast: 5,
  MobilePreventRepairNotify: 5,
  MobilePreventChangeNotify: 5,
  MobilePreventErrorNotify: 5,
};

const 영업_일반 = {
  ShareNotice: 2,
  MasterUser: 2,
  MasterClient: 2,
  MasterProduct: 2,
  MasterBOM: 2,
  MasterFacility: 2,
  MasterProcess: 2,
  MasterMold: 2,
  MasterCodeBad: 2,
  MasterCodeNonOP: 2,
  MasterFacilityParts: 2,
  MasterQualityStd: 2,
  MasterFacilityStd: 2,
  MasterStockStd: 2,
  MasterRecipe: 2,
  OrderAdd: 3,
  OrderCurrent: 3,
  OrderForecast: 3,
  OrderNotify: 3,
  OrderDelivery: 3,
  OrderOrder: 3,
  OrderOrderCurrent: 3,
  OrderFacilityParts: 3,
  OrderFacilityPartsCurrent: 3,
  ProductionPlanAdd: 3,
  ProductionTaskAdd: 3,
  ProductionTaskCurrent: 3,
  ProductionTaskReport: 3,
  ProductionBadRework: 3,
  ProcessLOT: 3,
  ProcessLOTTrack: 3,
  ProcessChecker: 3,
  ProcessPlate: 3,
  ProcessPrinter1: 3,
  ProcessPrinter2: 3,
  ProcessPrinter3: 3,
  ProcessPrinter4: 3,
  ProcessPrinter5: 3,
  ProcessPrinter6: 3,
  ProcessPrinter7: 3,
  ProcessPrinter8: 3,
  StockReceiveRaw: 3,
  StockWIPRaw: 3,
  StockWIPMonitorRaw: 3,
  StockUseRaw: 3,
  StockMonitorRaw: 3,
  StockReceiveHalf: 3,
  StockWIPHalf: 3,
  StockWIPMonitorHalf: 3,
  StockUseHalf: 3,
  StockMonitorHalf: 3,
  StockReceiveFinish: 3,
  StockMonitorFinish: 3,
  StockReceiveParts: 3,
  StockUseParts: 3,
  StockMonitorParts: 3,
  QualityStandard: 2,
  QualityReport: 2,
  QualityIncoming: 3,
  QualityProcess: 3,
  QualityShipment: 3,
  MoldUse: 3,
  MoldRepair: 3,
  MoldCheck: 3,
  MonitoringKPI1: 2,
  MonitoringKPI2: 2,
  MonitoringDaily: 2,
  MonitoringPrevent: 2,
  MonitoringMTBF: 2,
  MonitoringMTTR: 2,
  MonitoringOEE: 2,
  PreventPlan: 3,
  PreventDailyPlan: 3,
  PreventRepairPlan: 3,
  PreventLifePlan: 3,
  PreventForecast: 3,
  PreventNotice: 3,
  PreventErrorNotify: 3,
  PreventDailyNotify: 3,
  PreventRepairForecast: 3,
  PreventRepairNotify: 3,
  PreventChangeNotify: 3,
  AdminLog: 1,
  AlertOrderForecast: 1,
  AlertOrderNotify: 1,
  AlertPreventForecast: 1,
  AlertPreventNotice: 1,
  AlertPreventErrorNotify: 1,
  AlertPreventDailyNotify: 1,
  AlertPreventRepairForecast: 1,
  AlertPreventRepairNotify: 1,
  AlertPreventChangeNotify: 1,
  AlertStockSafeNotify: 1,
  MobileOrderCurrentForecast: 3,
  MobileOrderCurrentNotify: 3,
  MobileOrderTaskReport: 3,
  MobileStockReceive: 3,
  MobileStockDelivery: 3,
  MobileStockLOTPrint: 3,
  MobileStockLOTTrack: 3,
  MobileStockSafeNotify: 3,
  MobilePreventDailyCheck: 3,
  MobilePreventDailyCheckNotify: 3,
  MobilePreventForecast: 3,
  MobilePreventNotify: 3,
  MobilePreventRepairForecast: 3,
  MobilePreventRepairNotify: 3,
  MobilePreventChangeNotify: 3,
  MobilePreventErrorNotify: 3,
};

const 품질_관리자 = {
  ShareNotice: 5,
  MasterUser: 5,
  MasterClient: 5,
  MasterProduct: 5,
  MasterBOM: 5,
  MasterFacility: 5,
  MasterProcess: 5,
  MasterMold: 5,
  MasterCodeBad: 5,
  MasterCodeNonOP: 5,
  MasterFacilityParts: 5,
  MasterQualityStd: 5,
  MasterFacilityStd: 5,
  MasterStockStd: 5,
  MasterRecipe: 5,
  OrderAdd: 5,
  OrderCurrent: 5,
  OrderForecast: 5,
  OrderNotify: 5,
  OrderDelivery: 5,
  OrderOrder: 5,
  OrderOrderCurrent: 5,
  OrderFacilityParts: 5,
  OrderFacilityPartsCurrent: 5,
  ProductionPlanAdd: 5,
  ProductionTaskAdd: 5,
  ProductionTaskCurrent: 5,
  ProductionTaskReport: 5,
  ProductionBadRework: 5,
  ProcessLOT: 5,
  ProcessLOTTrack: 5,
  ProcessChecker: 5,
  ProcessPlate: 5,
  ProcessPrinter1: 5,
  ProcessPrinter2: 5,
  ProcessPrinter3: 5,
  ProcessPrinter4: 5,
  ProcessPrinter5: 5,
  ProcessPrinter6: 5,
  ProcessPrinter7: 5,
  ProcessPrinter8: 5,
  StockReceiveRaw: 5,
  StockWIPRaw: 5,
  StockWIPMonitorRaw: 5,
  StockUseRaw: 5,
  StockMonitorRaw: 5,
  StockReceiveHalf: 5,
  StockWIPHalf: 5,
  StockWIPMonitorHalf: 5,
  StockUseHalf: 5,
  StockMonitorHalf: 5,
  StockReceiveFinish: 5,
  StockMonitorFinish: 5,
  StockReceiveParts: 5,
  StockUseParts: 5,
  StockMonitorParts: 5,
  QualityStandard: 5,
  QualityReport: 5,
  QualityIncoming: 5,
  QualityProcess: 5,
  QualityShipment: 5,
  MoldUse: 5,
  MoldRepair: 5,
  MoldCheck: 5,
  MonitoringKPI1: 5,
  MonitoringKPI2: 5,
  MonitoringDaily: 5,
  MonitoringPrevent: 5,
  MonitoringMTBF: 5,
  MonitoringMTTR: 5,
  MonitoringOEE: 5,
  PreventPlan: 5,
  PreventDailyPlan: 5,
  PreventRepairPlan: 5,
  PreventLifePlan: 5,
  PreventForecast: 5,
  PreventNotice: 5,
  PreventErrorNotify: 5,
  PreventDailyNotify: 5,
  PreventRepairForecast: 5,
  PreventRepairNotify: 5,
  PreventChangeNotify: 5,
  AdminLog: 1,
  AlertOrderForecast: 1,
  AlertOrderNotify: 1,
  AlertPreventForecast: 1,
  AlertPreventNotice: 1,
  AlertPreventErrorNotify: 1,
  AlertPreventDailyNotify: 1,
  AlertPreventRepairForecast: 1,
  AlertPreventRepairNotify: 1,
  AlertPreventChangeNotify: 1,
  AlertStockSafeNotify: 1,
  MobileOrderCurrentForecast: 5,
  MobileOrderCurrentNotify: 5,
  MobileOrderTaskReport: 5,
  MobileStockReceive: 5,
  MobileStockDelivery: 5,
  MobileStockLOTPrint: 5,
  MobileStockLOTTrack: 5,
  MobileStockSafeNotify: 5,
  MobilePreventDailyCheck: 5,
  MobilePreventDailyCheckNotify: 5,
  MobilePreventForecast: 5,
  MobilePreventNotify: 5,
  MobilePreventRepairForecast: 5,
  MobilePreventRepairNotify: 5,
  MobilePreventChangeNotify: 5,
  MobilePreventErrorNotify: 5,
};

const 품질_일반 = {
  ShareNotice: 2,
  MasterUser: 2,
  MasterClient: 2,
  MasterProduct: 2,
  MasterBOM: 2,
  MasterFacility: 2,
  MasterProcess: 2,
  MasterMold: 2,
  MasterCodeBad: 2,
  MasterCodeNonOP: 2,
  MasterFacilityParts: 2,
  MasterQualityStd: 2,
  MasterFacilityStd: 2,
  MasterStockStd: 2,
  MasterRecipe: 2,
  OrderAdd: 3,
  OrderCurrent: 3,
  OrderForecast: 3,
  OrderNotify: 3,
  OrderDelivery: 3,
  OrderOrder: 3,
  OrderOrderCurrent: 3,
  OrderFacilityParts: 3,
  OrderFacilityPartsCurrent: 3,
  ProductionPlanAdd: 3,
  ProductionTaskAdd: 3,
  ProductionTaskCurrent: 3,
  ProductionTaskReport: 3,
  ProductionBadRework: 3,
  ProcessLOT: 3,
  ProcessLOTTrack: 3,
  ProcessChecker: 3,
  ProcessPlate: 3,
  ProcessPrinter1: 3,
  ProcessPrinter2: 3,
  ProcessPrinter3: 3,
  ProcessPrinter4: 3,
  ProcessPrinter5: 3,
  ProcessPrinter6: 3,
  ProcessPrinter7: 3,
  ProcessPrinter8: 3,
  StockReceiveRaw: 3,
  StockWIPRaw: 3,
  StockWIPMonitorRaw: 3,
  StockUseRaw: 3,
  StockMonitorRaw: 3,
  StockReceiveHalf: 3,
  StockWIPHalf: 3,
  StockWIPMonitorHalf: 3,
  StockUseHalf: 3,
  StockMonitorHalf: 3,
  StockReceiveFinish: 3,
  StockMonitorFinish: 3,
  StockReceiveParts: 3,
  StockUseParts: 3,
  StockMonitorParts: 3,
  QualityStandard: 2,
  QualityReport: 2,
  QualityIncoming: 3,
  QualityProcess: 3,
  QualityShipment: 3,
  MoldUse: 3,
  MoldRepair: 3,
  MoldCheck: 3,
  MonitoringKPI1: 2,
  MonitoringKPI2: 2,
  MonitoringDaily: 2,
  MonitoringPrevent: 2,
  MonitoringMTBF: 2,
  MonitoringMTTR: 2,
  MonitoringOEE: 2,
  PreventPlan: 3,
  PreventDailyPlan: 3,
  PreventRepairPlan: 3,
  PreventLifePlan: 3,
  PreventForecast: 3,
  PreventNotice: 3,
  PreventErrorNotify: 3,
  PreventDailyNotify: 3,
  PreventRepairForecast: 3,
  PreventRepairNotify: 3,
  PreventChangeNotify: 3,
  AdminLog: 1,
  AlertOrderForecast: 1,
  AlertOrderNotify: 1,
  AlertPreventForecast: 1,
  AlertPreventNotice: 1,
  AlertPreventErrorNotify: 1,
  AlertPreventDailyNotify: 1,
  AlertPreventRepairForecast: 1,
  AlertPreventRepairNotify: 1,
  AlertPreventChangeNotify: 1,
  AlertStockSafeNotify: 1,
  MobileOrderCurrentForecast: 3,
  MobileOrderCurrentNotify: 3,
  MobileOrderTaskReport: 3,
  MobileStockReceive: 3,
  MobileStockDelivery: 3,
  MobileStockLOTPrint: 3,
  MobileStockLOTTrack: 3,
  MobileStockSafeNotify: 3,
  MobilePreventDailyCheck: 3,
  MobilePreventDailyCheckNotify: 3,
  MobilePreventForecast: 3,
  MobilePreventNotify: 3,
  MobilePreventRepairForecast: 3,
  MobilePreventRepairNotify: 3,
  MobilePreventChangeNotify: 3,
  MobilePreventErrorNotify: 3,
};

const 생산_관리자 = {
  ShareNotice: 5,
  MasterUser: 5,
  MasterClient: 5,
  MasterProduct: 5,
  MasterBOM: 5,
  MasterFacility: 5,
  MasterProcess: 5,
  MasterMold: 5,
  MasterCodeBad: 5,
  MasterCodeNonOP: 5,
  MasterFacilityParts: 5,
  MasterQualityStd: 5,
  MasterFacilityStd: 5,
  MasterStockStd: 5,
  MasterRecipe: 5,
  OrderAdd: 5,
  OrderCurrent: 5,
  OrderForecast: 5,
  OrderNotify: 5,
  OrderDelivery: 5,
  OrderOrder: 5,
  OrderOrderCurrent: 5,
  OrderFacilityParts: 5,
  OrderFacilityPartsCurrent: 5,
  ProductionPlanAdd: 5,
  ProductionTaskAdd: 5,
  ProductionTaskCurrent: 5,
  ProductionTaskReport: 5,
  ProductionBadRework: 5,
  ProcessLOT: 5,
  ProcessLOTTrack: 5,
  ProcessChecker: 5,
  ProcessPlate: 5,
  ProcessPrinter1: 5,
  ProcessPrinter2: 5,
  ProcessPrinter3: 5,
  ProcessPrinter4: 5,
  ProcessPrinter5: 5,
  ProcessPrinter6: 5,
  ProcessPrinter7: 5,
  ProcessPrinter8: 5,
  StockReceiveRaw: 5,
  StockWIPRaw: 5,
  StockWIPMonitorRaw: 5,
  StockUseRaw: 5,
  StockMonitorRaw: 5,
  StockReceiveHalf: 5,
  StockWIPHalf: 5,
  StockWIPMonitorHalf: 5,
  StockUseHalf: 5,
  StockMonitorHalf: 5,
  StockReceiveFinish: 5,
  StockMonitorFinish: 5,
  StockReceiveParts: 5,
  StockUseParts: 5,
  StockMonitorParts: 5,
  QualityStandard: 5,
  QualityReport: 5,
  QualityIncoming: 5,
  QualityProcess: 5,
  QualityShipment: 5,
  MoldUse: 5,
  MoldRepair: 5,
  MoldCheck: 5,
  MonitoringKPI1: 5,
  MonitoringKPI2: 5,
  MonitoringDaily: 5,
  MonitoringPrevent: 5,
  MonitoringMTBF: 5,
  MonitoringMTTR: 5,
  MonitoringOEE: 5,
  PreventPlan: 5,
  PreventDailyPlan: 5,
  PreventRepairPlan: 5,
  PreventLifePlan: 5,
  PreventForecast: 5,
  PreventNotice: 5,
  PreventErrorNotify: 5,
  PreventDailyNotify: 5,
  PreventRepairForecast: 5,
  PreventRepairNotify: 5,
  PreventChangeNotify: 5,
  AdminLog: 1,
  AlertOrderForecast: 1,
  AlertOrderNotify: 1,
  AlertPreventForecast: 1,
  AlertPreventNotice: 1,
  AlertPreventErrorNotify: 1,
  AlertPreventDailyNotify: 1,
  AlertPreventRepairForecast: 1,
  AlertPreventRepairNotify: 1,
  AlertPreventChangeNotify: 1,
  AlertStockSafeNotify: 1,
  MobileOrderCurrentForecast: 5,
  MobileOrderCurrentNotify: 5,
  MobileOrderTaskReport: 5,
  MobileStockReceive: 5,
  MobileStockDelivery: 5,
  MobileStockLOTPrint: 5,
  MobileStockLOTTrack: 5,
  MobileStockSafeNotify: 5,
  MobilePreventDailyCheck: 5,
  MobilePreventDailyCheckNotify: 5,
  MobilePreventForecast: 5,
  MobilePreventNotify: 5,
  MobilePreventRepairForecast: 5,
  MobilePreventRepairNotify: 5,
  MobilePreventChangeNotify: 5,
  MobilePreventErrorNotify: 5,
};

const 생산_일반 = {
  ShareNotice: 2,
  MasterUser: 2,
  MasterClient: 2,
  MasterProduct: 2,
  MasterBOM: 2,
  MasterFacility: 2,
  MasterProcess: 2,
  MasterMold: 2,
  MasterCodeBad: 2,
  MasterCodeNonOP: 2,
  MasterFacilityParts: 2,
  MasterQualityStd: 2,
  MasterFacilityStd: 2,
  MasterStockStd: 2,
  MasterRecipe: 2,
  OrderAdd: 3,
  OrderCurrent: 3,
  OrderForecast: 3,
  OrderNotify: 3,
  OrderDelivery: 3,
  OrderOrder: 3,
  OrderOrderCurrent: 3,
  OrderFacilityParts: 3,
  OrderFacilityPartsCurrent: 3,
  ProductionPlanAdd: 3,
  ProductionTaskAdd: 3,
  ProductionTaskCurrent: 3,
  ProductionTaskReport: 3,
  ProductionBadRework: 3,
  ProcessLOT: 3,
  ProcessLOTTrack: 3,
  ProcessChecker: 3,
  ProcessPlate: 3,
  ProcessPrinter1: 3,
  ProcessPrinter2: 3,
  ProcessPrinter3: 3,
  ProcessPrinter4: 3,
  ProcessPrinter5: 3,
  ProcessPrinter6: 3,
  ProcessPrinter7: 3,
  ProcessPrinter8: 3,
  StockReceiveRaw: 3,
  StockWIPRaw: 3,
  StockWIPMonitorRaw: 3,
  StockUseRaw: 3,
  StockMonitorRaw: 3,
  StockReceiveHalf: 3,
  StockWIPHalf: 3,
  StockWIPMonitorHalf: 3,
  StockUseHalf: 3,
  StockMonitorHalf: 3,
  StockReceiveFinish: 3,
  StockMonitorFinish: 3,
  StockReceiveParts: 3,
  StockUseParts: 3,
  StockMonitorParts: 3,
  QualityStandard: 2,
  QualityReport: 2,
  QualityIncoming: 3,
  QualityProcess: 3,
  QualityShipment: 3,
  MoldUse: 3,
  MoldRepair: 3,
  MoldCheck: 3,
  MonitoringKPI1: 2,
  MonitoringKPI2: 2,
  MonitoringDaily: 2,
  MonitoringPrevent: 2,
  MonitoringMTBF: 2,
  MonitoringMTTR: 2,
  MonitoringOEE: 2,
  PreventPlan: 3,
  PreventDailyPlan: 3,
  PreventRepairPlan: 3,
  PreventLifePlan: 3,
  PreventForecast: 3,
  PreventNotice: 3,
  PreventErrorNotify: 3,
  PreventDailyNotify: 3,
  PreventRepairForecast: 3,
  PreventRepairNotify: 3,
  PreventChangeNotify: 3,
  AdminLog: 1,
  AlertOrderForecast: 1,
  AlertOrderNotify: 1,
  AlertPreventForecast: 1,
  AlertPreventNotice: 1,
  AlertPreventErrorNotify: 1,
  AlertPreventDailyNotify: 1,
  AlertPreventRepairForecast: 1,
  AlertPreventRepairNotify: 1,
  AlertPreventChangeNotify: 1,
  AlertStockSafeNotify: 1,
  MobileOrderCurrentForecast: 3,
  MobileOrderCurrentNotify: 3,
  MobileOrderTaskReport: 3,
  MobileStockReceive: 3,
  MobileStockDelivery: 3,
  MobileStockLOTPrint: 3,
  MobileStockLOTTrack: 3,
  MobileStockSafeNotify: 3,
  MobilePreventDailyCheck: 3,
  MobilePreventDailyCheckNotify: 3,
  MobilePreventForecast: 3,
  MobilePreventNotify: 3,
  MobilePreventRepairForecast: 3,
  MobilePreventRepairNotify: 3,
  MobilePreventChangeNotify: 3,
  MobilePreventErrorNotify: 3,
};

const 구매_관리자 = {
  ShareNotice: 5,
  MasterUser: 5,
  MasterClient: 5,
  MasterProduct: 5,
  MasterBOM: 5,
  MasterFacility: 5,
  MasterProcess: 5,
  MasterMold: 5,
  MasterCodeBad: 5,
  MasterCodeNonOP: 5,
  MasterFacilityParts: 5,
  MasterQualityStd: 5,
  MasterFacilityStd: 5,
  MasterStockStd: 5,
  MasterRecipe: 5,
  OrderAdd: 5,
  OrderCurrent: 5,
  OrderForecast: 5,
  OrderNotify: 5,
  OrderDelivery: 5,
  OrderOrder: 5,
  OrderOrderCurrent: 5,
  OrderFacilityParts: 5,
  OrderFacilityPartsCurrent: 5,
  ProductionPlanAdd: 5,
  ProductionTaskAdd: 5,
  ProductionTaskCurrent: 5,
  ProductionTaskReport: 5,
  ProductionBadRework: 5,
  ProcessLOT: 5,
  ProcessLOTTrack: 5,
  ProcessChecker: 5,
  ProcessPlate: 5,
  ProcessPrinter1: 5,
  ProcessPrinter2: 5,
  ProcessPrinter3: 5,
  ProcessPrinter4: 5,
  ProcessPrinter5: 5,
  ProcessPrinter6: 5,
  ProcessPrinter7: 5,
  ProcessPrinter8: 5,
  StockReceiveRaw: 5,
  StockWIPRaw: 5,
  StockWIPMonitorRaw: 5,
  StockUseRaw: 5,
  StockMonitorRaw: 5,
  StockReceiveHalf: 5,
  StockWIPHalf: 5,
  StockWIPMonitorHalf: 5,
  StockUseHalf: 5,
  StockMonitorHalf: 5,
  StockReceiveFinish: 5,
  StockMonitorFinish: 5,
  StockReceiveParts: 5,
  StockUseParts: 5,
  StockMonitorParts: 5,
  QualityStandard: 5,
  QualityReport: 5,
  QualityIncoming: 5,
  QualityProcess: 5,
  QualityShipment: 5,
  MoldUse: 5,
  MoldRepair: 5,
  MoldCheck: 5,
  MonitoringKPI1: 5,
  MonitoringKPI2: 5,
  MonitoringDaily: 5,
  MonitoringPrevent: 5,
  MonitoringMTBF: 5,
  MonitoringMTTR: 5,
  MonitoringOEE: 5,
  PreventPlan: 5,
  PreventDailyPlan: 5,
  PreventRepairPlan: 5,
  PreventLifePlan: 5,
  PreventForecast: 5,
  PreventNotice: 5,
  PreventErrorNotify: 5,
  PreventDailyNotify: 5,
  PreventRepairForecast: 5,
  PreventRepairNotify: 5,
  PreventChangeNotify: 5,
  AdminLog: 1,
  AlertOrderForecast: 1,
  AlertOrderNotify: 1,
  AlertPreventForecast: 1,
  AlertPreventNotice: 1,
  AlertPreventErrorNotify: 1,
  AlertPreventDailyNotify: 1,
  AlertPreventRepairForecast: 1,
  AlertPreventRepairNotify: 1,
  AlertPreventChangeNotify: 1,
  AlertStockSafeNotify: 1,
  MobileOrderCurrentForecast: 5,
  MobileOrderCurrentNotify: 5,
  MobileOrderTaskReport: 5,
  MobileStockReceive: 5,
  MobileStockDelivery: 5,
  MobileStockLOTPrint: 5,
  MobileStockLOTTrack: 5,
  MobileStockSafeNotify: 5,
  MobilePreventDailyCheck: 5,
  MobilePreventDailyCheckNotify: 5,
  MobilePreventForecast: 5,
  MobilePreventNotify: 5,
  MobilePreventRepairForecast: 5,
  MobilePreventRepairNotify: 5,
  MobilePreventChangeNotify: 5,
  MobilePreventErrorNotify: 5,
};

const 구매_일반 = {
  ShareNotice: 1,
  MasterUser: 1,
  MasterClient: 1,
  MasterProduct: 1,
  MasterBOM: 1,
  MasterFacility: 1,
  MasterProcess: 1,
  MasterMold: 1,
  MasterCodeBad: 1,
  MasterCodeNonOP: 1,
  MasterFacilityParts: 1,
  MasterQualityStd: 1,
  MasterFacilityStd: 1,
  MasterStockStd: 1,
  MasterRecipe: 1,
  OrderAdd: 1,
  OrderCurrent: 1,
  OrderForecast: 1,
  OrderNotify: 1,
  OrderDelivery: 1,
  OrderOrder: 1,
  OrderOrderCurrent: 1,
  OrderFacilityParts: 1,
  OrderFacilityPartsCurrent: 1,
  ProductionPlanAdd: 1,
  ProductionTaskAdd: 1,
  ProductionTaskCurrent: 1,
  ProductionTaskReport: 1,
  ProductionBadRework: 1,
  ProcessLOT: 1,
  ProcessLOTTrack: 1,
  ProcessChecker: 1,
  ProcessPlate: 1,
  ProcessPrinter1: 1,
  ProcessPrinter2: 1,
  ProcessPrinter3: 1,
  ProcessPrinter4: 1,
  ProcessPrinter5: 1,
  ProcessPrinter6: 1,
  ProcessPrinter7: 1,
  ProcessPrinter8: 1,
  StockReceiveRaw: 1,
  StockWIPRaw: 1,
  StockWIPMonitorRaw: 1,
  StockUseRaw: 1,
  StockMonitorRaw: 1,
  StockReceiveHalf: 1,
  StockWIPHalf: 1,
  StockWIPMonitorHalf: 1,
  StockUseHalf: 1,
  StockMonitorHalf: 1,
  StockReceiveFinish: 1,
  StockMonitorFinish: 1,
  StockReceiveParts: 1,
  StockUseParts: 1,
  StockMonitorParts: 1,
  QualityStandard: 1,
  QualityReport: 1,
  QualityIncoming: 1,
  QualityProcess: 1,
  QualityShipment: 1,
  MoldUse: 1,
  MoldRepair: 1,
  MoldCheck: 1,
  MonitoringKPI1: 1,
  MonitoringKPI2: 1,
  MonitoringDaily: 1,
  MonitoringPrevent: 1,
  MonitoringMTBF: 1,
  MonitoringMTTR: 1,
  MonitoringOEE: 1,
  PreventPlan: 1,
  PreventDailyPlan: 1,
  PreventRepairPlan: 1,
  PreventLifePlan: 1,
  PreventForecast: 1,
  PreventNotice: 1,
  PreventErrorNotify: 1,
  PreventDailyNotify: 1,
  PreventRepairForecast: 1,
  PreventRepairNotify: 1,
  PreventChangeNotify: 1,
  AdminLog: 1,
  AlertOrderForecast: 1,
  AlertOrderNotify: 1,
  AlertPreventForecast: 1,
  AlertPreventNotice: 1,
  AlertPreventErrorNotify: 1,
  AlertPreventDailyNotify: 1,
  AlertPreventRepairForecast: 1,
  AlertPreventRepairNotify: 1,
  AlertPreventChangeNotify: 1,
  AlertStockSafeNotify: 1,
  MobileOrderCurrentForecast: 1,
  MobileOrderCurrentNotify: 1,
  MobileOrderTaskReport: 1,
  MobileStockReceive: 1,
  MobileStockDelivery: 1,
  MobileStockLOTPrint: 1,
  MobileStockLOTTrack: 1,
  MobileStockSafeNotify: 1,
  MobilePreventDailyCheck: 1,
  MobilePreventDailyCheckNotify: 1,
  MobilePreventForecast: 1,
  MobilePreventNotify: 1,
  MobilePreventRepairForecast: 1,
  MobilePreventRepairNotify: 1,
  MobilePreventChangeNotify: 1,
  MobilePreventErrorNotify: 1,
};

// const 구매_일반 = {
//   ShareNotice: 2,
//   MasterUser: 2,
//   MasterClient: 2,
//   MasterProduct: 2,
//   MasterBOM: 2,
//   MasterFacility: 2,
//   MasterProcess: 2,
//   MasterMold: 2,
//   MasterCodeBad: 2,
//   MasterCodeNonOP: 2,
//   MasterFacilityParts: 2,
//   MasterQualityStd: 2,
//   MasterFacilityStd: 2,
//   MasterStockStd: 2,
//   MasterRecipe: 2,
//   OrderAdd: 3,
//   OrderCurrent: 3,
//   OrderForecast: 3,
//   OrderNotify: 3,
//   OrderDelivery: 3,
//   OrderOrder: 3,
//   OrderOrderCurrent: 3,
//   OrderFacilityParts: 3,
//   OrderFacilityPartsCurrent: 3,
//   ProductionPlanAdd: 3,
//   ProductionTaskAdd: 3,
//   ProductionTaskCurrent: 3,
//   ProductionTaskReport: 3,
//   ProductionBadRework: 3,
//   ProcessLOT: 3,
//   ProcessLOTTrack: 3,
//   ProcessChecker: 3,
//   ProcessPlate: 3,
//   ProcessPrinter1: 3,
//   ProcessPrinter2: 3,
//   ProcessPrinter3: 3,
//   ProcessPrinter4: 3,
//   ProcessPrinter5: 3,
//   ProcessPrinter6: 3,
//   ProcessPrinter7: 3,
//   ProcessPrinter8: 3,
//   StockReceiveRaw: 3,
//   StockWIPRaw: 3,
//   StockWIPMonitorRaw: 3,
//   StockUseRaw: 3,
//   StockMonitorRaw: 3,
//   StockReceiveHalf: 3,
//   StockWIPHalf: 3,
//   StockWIPMonitorHalf: 3,
//   StockUseHalf: 3,
//   StockMonitorHalf: 3,
//   StockReceiveFinish: 3,
//   StockMonitorFinish: 3,
//   StockReceiveParts: 3,
//   StockUseParts: 3,
//   StockMonitorParts: 3,
//   QualityStandard: 2,
//   QualityReport: 2,
//   QualityIncoming: 3,
//   QualityProcess: 3,
//   QualityShipment: 3,
//   MoldUse: 3,
//   MoldRepair: 3,
//   MoldCheck: 3,
//   MonitoringKPI1: 2,
//   MonitoringKPI2: 2,
//   MonitoringDaily: 2,
//   MonitoringPrevent: 2,
//   MonitoringMTBF: 2,
//   MonitoringMTTR: 2,
//   MonitoringOEE: 2,
//   PreventPlan: 3,
//   PreventDailyPlan: 3,
//   PreventRepairPlan: 3,
//   PreventLifePlan: 3,
//   PreventForecast: 3,
//   PreventNotice: 3,
//   PreventErrorNotify: 3,
//   PreventDailyNotify: 3,
//   PreventRepairForecast: 3,
//   PreventRepairNotify: 3,
//   PreventChangeNotify: 3,
//   AdminLog: 1,
//   AlertOrderForecast: 1,
//   AlertOrderNotify: 1,
//   AlertPreventForecast: 1,
//   AlertPreventNotice: 1,
//   AlertPreventErrorNotify: 1,
//   AlertPreventDailyNotify: 1,
//   AlertPreventRepairForecast: 1,
//   AlertPreventRepairNotify: 1,
//   AlertPreventChangeNotify: 1,
//   AlertStockSafeNotify: 1,
//   MobileOrderCurrentForecast: 3,
//   MobileOrderCurrentNotify: 3,
//   MobileOrderTaskReport: 3,
//   MobileStockReceive: 3,
//   MobileStockDelivery: 3,
//   MobileStockLOTPrint: 3,
//   MobileStockLOTTrack: 3,
//   MobileStockSafeNotify: 3,
//   MobilePreventDailyCheck: 3,
//   MobilePreventDailyCheckNotify: 3,
//   MobilePreventForecast: 3,
//   MobilePreventNotify: 3,
//   MobilePreventRepairForecast: 3,
//   MobilePreventRepairNotify: 3,
//   MobilePreventChangeNotify: 3,
//   MobilePreventErrorNotify: 3,
// };

export {
  시스템_개발자,
  시스템_관리자,
  구매_관리자,
  구매_일반,
  영업_관리자,
  영업_일반,
  품질_관리자,
  품질_일반,
  생산_관리자,
  생산_일반,
};
