import { createApp } from "vue";
import { reactive } from "vue";
import { createPinia } from "pinia";
import App from "./App.vue";
import router from "./router";
import Vue3Toasity from "vue3-toastify";
import "vue3-toastify/dist/index.css";
import "./assets/css/app.css";

const app = createApp(App);
app.use(router);
app.use(createPinia());
app.use(Vue3Toasity, {
  dangerouslyHTMLString: true,
  autoClose: 2000,
});

app.mount("#app");

app.config.globalProperties.gstate = reactive({
  account: {
    id: null,
    name: "",
    part: "",
    rank: "",
    auth: "",
  },
  form: {
    loginId: "",
    loginPw: "",
  },
  level: {
    AdminLog: 4,
    MasterBOM: 4,
    MasterClient: 4,
    MasterCodeBad: 4,
    MasterCodeNonOP: 4,
    MasterFacility: 4,
    MasterFacilityParts: 4,
    MasterFacilityStd: 4,
    MasterProcess: 4,
    MasterProduct: 4,
    MasterQualityStd: 4,
    MasterRecipe: 4,
    MasterStockStd: 4,
    MasterUser: 4,
    MonitoringDaily: 4,
    MonitoringKPI: 4,
    MonitoringMTBF: 4,
    MonitoringMTTR: 4,
    MonitoringOEE: 4,
    MonitoringOverall: 4,
    MonitoringPrevent: 4,
    MonitoringProcess: 4,
    MonitoringProduction: 4,
    MonitoringStock: 4,
    OrderAdd: 4,
    OrderCurrent: 4,
    OrderDelivery: 4,
    OrderFacilityParts: 4,
    OrderFacilityPartsCurrent: 4,
    OrderForecast: 4,
    OrderNotify: 4,
    OrderOrder: 4,
    OrderOrderCurrent: 4,
    PreventChangeNotify: 4,
    PreventDailyNotify: 4,
    PreventDailyPlan: 4,
    PreventErrorNotify: 4,
    PreventForecast: 4,
    PreventLifePlan: 4,
    PreventNotice: 4,
    PreventPlan: 4,
    PreventRepairForecast: 4,
    PreventRepairNotify: 4,
    PreventRepairPlan: 4,
    ProcessChecker: 4,
    ProcessLOT: 4,
    ProcessLOTTrack: 4,
    ProcessPlate: 4,
    ProcessPrinter1: 4,
    ProcessPrinter2: 4,
    ProcessPrinter3: 4,
    ProcessPrinter4: 4,
    ProcessPrinter5: 4,
    ProcessPrinter6: 4,
    ProcessPrinter7: 4,
    ProcessPrinter8: 4,
    ProductionBadRework: 4,
    ProductionPlanAdd: 4,
    ProductionTaskAdd: 4,
    ProductionTaskAddInsert: 4,
    ProductionTaskCurrent: 4,
    ProductionTaskReport: 4,
    QualityInadequate: 4,
    QualityIncoming: 4,
    QualityProcess: 4,
    QualityReport: 4,
    QualityShipment: 4,
    QualityStandard: 4,
    ShareNotice: 4,
    StockMonitorFinish: 4,
    StockMonitorHalf: 4,
    StockMonitorParts: 4,
    StockMonitorRaw: 4,
    StockReceiveFinish: 4,
    StockReceiveHalf: 4,
    StockReceiveParts: 4,
    StockReceiveRaw: 4,
    StockUseHalf: 4,
    StockUseParts: 4,
    StockUseRaw: 4,
    StockWIPHalf: 4,
    StockWIPMonitorHalf: 4,
    StockWIPMonitorRaw: 4,
    StockWIPRaw: 4,
  },
  debug: {
    active: null,
  },
});
